"""Codex target adapter with deterministic project-scoped output."""

from __future__ import annotations

import hashlib
import json
import re
from pathlib import Path
from typing import Any

import yaml

from ..bindings import CodexBinding
from .. import __version__
from ..generator import (
    _output_tree_violations,
    _public_source_definition,
    _render_files,
    generate_harness,
)
from ..hir import HIR
from ..io import atomic_write_text, canonical_json, dump_json
from ..security import scan_generated_artifacts
from .base import CompilePlan, ConformanceResult, PlannedArtifact


class CodexAdapter:
    name = "codex"
    version = "0.1.0"

    def __init__(self, binding: CodexBinding):
        self.binding = binding

    def plan(self, hir: HIR) -> CompilePlan:
        allowed_capabilities = set(
            hir.canonical_semantics["governance"]["permissions"]["tools"]["allowedIds"]
        )
        bound_commands = set(self.binding.command_bindings)
        missing = sorted(allowed_capabilities - bound_commands)
        extra = sorted(bound_commands - allowed_capabilities)
        if missing or extra:
            raise ValueError(
                "Codex command bindings must exactly cover governance-allowed "
                f"capabilities; missing={missing}, unknown-or-denied={extra}"
            )
        semantics = hir.canonical_semantics
        required_external = {"environment", "filesystem", "network", "process"}
        required_external.update(
            item["resource"] for item in semantics["resources"].get("budgets", [])
            if item.get("hard") and item.get("resource") != "tool-calls"
        )
        missing_external = sorted(
            required_external - set(self.binding.externally_enforced_resources)
        )
        if missing_external:
            raise ValueError(
                "Codex binding must name every required outer enforcement boundary; "
                f"missing={missing_external}"
            )
        planned = (
            PlannedArtifact(
                path=".codex/config.toml", media_type="application/toml",
                source_pointers=("target-binding:/settings",), transformation="rendered",
            ),
            PlannedArtifact(
                path=".hdp/hir.json", media_type="application/json",
                source_pointers=("/",), transformation="normalized",
            ),
            PlannedArtifact(
                path=".hdp/compile-plan.json", media_type="application/json",
                source_pointers=("/", "target-binding:/"), transformation="planned",
            ),
            PlannedArtifact(
                path=".hdp/synthesis-records.json", media_type="application/json",
                source_pointers=("factory-contract:/bounded-assisted-synthesis",),
                transformation="synthesis-ledger",
            ),
            PlannedArtifact(
                path="HarnessCard.md", media_type="text/markdown",
                source_pointers=("/purpose", "/governance", "/evaluation", "/limitations"),
                transformation="rendered",
            ),
        )
        return CompilePlan(
            adapter=self.name, adapter_version=self.version,
            hir_digest=hir.digest(), artifacts=planned,
        )

    def _config_toml(self) -> str:
        settings = self.binding.settings
        lines = [
            "# Generated by HDP Codex adapter. Project-scoped settings only.",
            f'model = {json.dumps(settings.model)}',
            f'model_reasoning_effort = {json.dumps(settings.reasoning_effort)}',
            f'approval_policy = {json.dumps(settings.approval_policy)}',
            f'sandbox_mode = {json.dumps(settings.sandbox_mode)}',
        ]
        for server in sorted(self.binding.mcp_servers, key=lambda item: item.id):
            lines.extend(["", f"[mcp_servers.{server.id}]", f"required = {str(server.required).lower()}"])
            if server.transport == "stdio":
                lines.append(f"command = {json.dumps(server.command)}")
                lines.append(f"args = {json.dumps(server.args)}")
            else:
                lines.append(f"url = {json.dumps(server.url)}")
            lines.append(f"startup_timeout_sec = {server.startup_timeout_seconds}")
            lines.append(f"tool_timeout_sec = {server.tool_timeout_seconds}")
            if server.enabled_tools:
                lines.append(f"enabled_tools = {json.dumps(server.enabled_tools)}")
            if server.disabled_tools:
                lines.append(f"disabled_tools = {json.dumps(server.disabled_tools)}")
        return "\n".join(lines) + "\n"

    def _harness_card(self, hir: HIR) -> str:
        semantics = hir.canonical_semantics
        outcomes = "\n".join(
            f"- {item['statement']}" for item in semantics["purpose"]["intendedOutcomes"]
        )
        limitations = "\n".join(
            f"- {item['statement']}" for item in semantics.get("limitations", [])
        ) or "- None declared."
        return f"""# HarnessCard

Harness: {semantics['metadata']['title']}  
HDP: `{semantics['metadata']['id']}` version `{semantics['metadata']['version']}`  
HIR: `{hir.hir_version}` digest `{hir.digest()}`  
Target: Codex adapter `{self.version}`

## Intended outcomes

{outcomes}

## Runtime and authority

- Model: `{self.binding.settings.model}` with `{self.binding.settings.reasoning_effort}` reasoning.
- Sandbox requested: `{self.binding.settings.sandbox_mode}`.
- Approval policy requested: `{self.binding.settings.approval_policy}`.
- Generated command controls are evidence recorders, not an OS sandbox.
- External evaluators, not the generated harness, decide behavioural acceptance.

## Limitations

{limitations}

## Attestation claim

Release statements are unsigned digest-only metadata. They establish detectable
integrity, not builder identity, non-repudiation, SLSA level, or certification.
"""

    def _runtime_policy_overlay(self) -> dict[str, Any]:
        return {
            "allowedExecutables": sorted({
                executable
                for values in self.binding.command_bindings.values()
                for executable in values
            }),
            "commandBindings": self.binding.command_bindings,
            "externallyEnforcedResources": self.binding.externally_enforced_resources,
            "enforcementBoundary": (
                "defence-in-depth precheck and evidence recorder; outer OS/Codex sandbox "
                "is required for filesystem, process, environment, and network isolation"
            ),
        }

    @staticmethod
    def _public_hir(hir: HIR) -> dict[str, Any]:
        projected = hir.canonical_dict()
        projected["canonical_semantics"] = _public_source_definition(hir.canonical_semantics)
        return projected

    def _additional_files(
        self, hir: HIR, plan: CompilePlan
    ) -> tuple[dict[str, str], dict[str, list[str]]]:
        additional = {
            ".codex/config.toml": self._config_toml(),
            ".hdp/hir.json": dump_json(self._public_hir(hir)),
            ".hdp/compile-plan.json": dump_json(plan.model_dump(mode="json")),
            ".hdp/synthesis-records.json": dump_json({"version": "0.1.0", "records": []}),
            "HarnessCard.md": self._harness_card(hir),
        }
        source_map = {item.path: list(item.source_pointers) for item in plan.artifacts}
        return additional, source_map

    def _expected_files(
        self, hir: HIR, plan: CompilePlan
    ) -> tuple[dict[str, str], dict[str, list[str]]]:
        files, source_map = _render_files(
            hir.canonical_semantics, self._runtime_policy_overlay()
        )
        additional, additional_source_map = self._additional_files(hir, plan)
        files.update(additional)
        source_map.update(additional_source_map)
        source_map[".hdp/source-map.json"] = ["factory-contract:/artifact-source-map"]
        files[".hdp/source-map.json"] = dump_json(source_map)
        return files, source_map

    def render(self, hir: HIR, output: Path, *, force_generated: bool = False) -> dict[str, Any]:
        plan = self.plan(hir)
        additional, source_map = self._additional_files(hir, plan)
        definition_path = _materialize_definition(hir, output)
        try:
            return generate_harness(
                definition_path, output,
                force_generated=force_generated,
                additional_files=additional,
                additional_source_map=source_map,
                runtime_policy_overlay=self._runtime_policy_overlay(),
            )
        finally:
            definition_path.unlink(missing_ok=True)

    def static_check(self, output: Path, hir: HIR) -> ConformanceResult:
        checks: list[dict[str, Any]] = []
        tree_violations = (
            ["output-root-symlink"] if output.is_symlink() else []
        ) + _output_tree_violations(output)
        checks.append({
            "id": "output-tree-regular-files",
            "passed": not tree_violations,
            "violations": tree_violations,
        })
        if tree_violations:
            return ConformanceResult(status="fail", checks=tuple(checks))

        plan = self.plan(hir)
        expected_files, expected_source_map = self._expected_files(hir, plan)
        required = ["AGENTS.md", ".codex/config.toml", ".hdp/hir.json", "HarnessCard.md"]
        for relative in required:
            checks.append({"id": f"file:{relative}", "passed": (output / relative).is_file()})
        skill_paths = sorted(output.glob(".agents/skills/*/SKILL.md"))
        skill_ok = bool(skill_paths)
        for path in skill_paths:
            raw = path.read_text(encoding="utf-8")
            try:
                frontmatter = yaml.safe_load(raw.split("---", 2)[1])
            except Exception:
                skill_ok = False
                continue
            name = frontmatter.get("name") if isinstance(frontmatter, dict) else None
            description = frontmatter.get("description") if isinstance(frontmatter, dict) else None
            skill_ok = skill_ok and name == path.parent.name
            skill_ok = skill_ok and bool(re.fullmatch(r"[a-z0-9]+(?:-[a-z0-9]+)*", name or ""))
            skill_ok = skill_ok and 1 <= len(name or "") <= 64 and 1 <= len(description or "") <= 1024
            skill_ok = skill_ok and "TODO" not in raw
        checks.append({"id": "agent-skill-structure", "passed": skill_ok})
        agents_size = (output / "AGENTS.md").stat().st_size if (output / "AGENTS.md").exists() else 0
        checks.append({"id": "agents-size", "passed": 0 < agents_size <= 32768, "bytes": agents_size})
        config = (output / ".codex/config.toml").read_text(encoding="utf-8") if (output / ".codex/config.toml").exists() else ""
        checks.append({"id": "danger-full-access-denied", "passed": "danger-full-access" not in config})
        checks.append({
            "id": "config-exact",
            "passed": config == expected_files[".codex/config.toml"],
        })

        def read_json(relative: str) -> tuple[dict[str, Any], str | None]:
            try:
                value = json.loads((output / relative).read_text(encoding="utf-8"))
                if not isinstance(value, dict):
                    return {}, "top level is not an object"
                return value, None
            except (OSError, json.JSONDecodeError) as exc:
                return {}, str(exc)

        hir_value, hir_error = read_json(".hdp/hir.json")
        checks.append({
            "id": "hir-exact",
            "passed": hir_error is None and hir_value == self._public_hir(hir),
            "error": hir_error,
        })
        checks.append({
            "id": "hir-subject",
            "passed": hir_error is None and hir_value.get("source_digest") == hir.source_digest,
        })

        runtime_policy, runtime_error = read_json(".hdp/runtime-policy.json")
        unsupported = runtime_policy.get("unsupportedHardBudgets", [])
        checks.append({
            "id": "hard-budget-binding",
            "passed": runtime_error is None and unsupported == [],
            "unsupported": unsupported if isinstance(unsupported, list) else ["invalid-policy"],
            "error": runtime_error,
        })
        unsupported_controls = runtime_policy.get("unsupportedEnforcementResources", [])
        checks.append({
            "id": "external-control-binding",
            "passed": runtime_error is None and unsupported_controls == [],
            "unsupported": (
                unsupported_controls
                if isinstance(unsupported_controls, list) else ["invalid-policy"]
            ),
            "error": runtime_error,
        })

        source_map, source_map_error = read_json(".hdp/source-map.json")
        checks.append({
            "id": "source-map-exact",
            "passed": source_map_error is None and source_map == expected_source_map,
            "error": source_map_error,
        })

        expected_artifacts = [
            {
                "path": relative,
                "sha256": hashlib.sha256(content.encode("utf-8")).hexdigest(),
                "sourceFields": expected_source_map.get(relative, []),
            }
            for relative, content in sorted(expected_files.items())
        ]
        expected_manifest_fields = {
            "manifestVersion": "1",
            "generator": {"name": "harness-factory", "version": __version__},
            "source": {
                "id": hir.canonical_semantics["metadata"]["id"],
                "version": hir.canonical_semantics["metadata"]["version"],
                "sha256": hashlib.sha256(
                    canonical_json(hir.canonical_semantics).encode("utf-8")
                ).hexdigest(),
            },
            "artifacts": expected_artifacts,
            "staleGeneratedArtifactsRetained": [],
            "manualExtensionRoot": "manual/",
        }
        manifest, manifest_error = read_json(".hdp/manifest.json")
        checks.append({
            "id": "manifest-exact",
            "passed": manifest_error is None and manifest == expected_manifest_fields,
            "error": manifest_error,
        })
        artifact_mismatches = sorted(
            relative
            for relative, content in expected_files.items()
            if not (output / relative).is_file()
            or hashlib.sha256((output / relative).read_bytes()).hexdigest()
            != hashlib.sha256(content.encode("utf-8")).hexdigest()
        )
        checks.append({
            "id": "generated-artifacts-exact",
            "passed": not artifact_mismatches,
            "mismatches": artifact_mismatches,
        })
        unmapped = sorted(
            item["path"] for item in expected_artifacts
            if not expected_source_map.get(item["path"]) or not item.get("sourceFields")
        )
        checks.append({"id": "source-map-total", "passed": not unmapped, "unmapped": unmapped})
        secret_findings = scan_generated_artifacts(
            output, {"artifacts": expected_artifacts}
        )
        checks.append({
            "id": "generated-secret-patterns", "passed": not secret_findings,
            "findings": secret_findings,
        })
        return ConformanceResult(
            status="pass" if all(item["passed"] for item in checks) else "fail",
            checks=tuple(checks),
        )


def _materialize_definition(hir: HIR, output: Path) -> Path:
    """Write the canonical input beside generated metadata for the legacy renderer."""
    scratch = output.parent / f".{output.name}.resolved-hdp.json"
    atomic_write_text(scratch, dump_json(hir.canonical_semantics))
    return scratch
